package UserInterface.Form;

import java.util.Random;

public class PanelInicio extends javax.swing.JPanel {

    /**
     * Creates new form PanelInicio
     */
    public PanelInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        int numero = generarNumeroAleatorio(4);
        String ruta = "/UserInterface/Resource/Image/Fondo" + numero + ".png";
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(ruta)));

        //jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\jonat\\eclipse-workspace\\ProyectoEDA\\src\\UserInterface\\Resource\\Image\\Fondo"+generarNumeroAleatorio(4)+".png"));
        //jLabel1.setIcon(new javax.swing.ImageIcon("/Resource/Image/Fondo"+generarNumeroAleatorio(4)+".png"));
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    public static int generarNumeroAleatorio(int max) {
        if (max < 1) {
            throw new IllegalArgumentException("El número máximo debe ser al menos 1.");
        }
        Random random = new Random();
        return random.nextInt(max) + 1; // devuelve un número entre 1 y max (incluidos)
    }
    
    
    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    // End of variables declaration                   
}
