package UserInterface.Form;

import java.awt.Color;
import java.awt.event.ActionEvent;
import javax.swing.Timer;

/**
 *
 * @author jonat
 */
public class Splash extends javax.swing.JFrame {

    private Color mTransparent;
    /**
     * Creates new form Splash
     */
    public Splash(int n) {
        mTransparent = new Color(0,0,0,0);
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        setBackground(Color.yellow);
        ImageDecore mFondo;
        if(n == 1){
            mFondo = new ImageDecore(pnlBackground, "../Resource/Logo/Picture1.png");
        }else{
            mFondo = new ImageDecore(pnlBackground, "../Resource/Logo/Picture3.png");
        }
        pnlBackground.add(mFondo).repaint();
        
        progressBarIni(n);
    }

    private void progressBarIni(int n){
        Timer mtimer = new Timer(45, (ActionEvent e) -> {
            pbCarga.setValue(pbCarga.getValue()+1);
            pbCarga.setStringPainted(true);
            pbCarga.setString("Cargando ..."+ pbCarga.getValue()+"%");
            pbCarga.setBackground(Color.orange);
            if(n!=1){
                pbCarga.setLocation(130, 450); /// Posiciona la barra de progreso
                pbCarga.setBackground(Color.white);
                //pbCarga.setBackground(Color.pink);
            }
        });
        mtimer.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        pbCarga = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(pbCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap(305, Short.MAX_VALUE)
                .addComponent(pbCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar pbCarga;
    private javax.swing.JPanel pnlBackground;
    // End of variables declaration//GEN-END:variables
}
